sudo: required
services:
  - docker
  
before_install:
  - docker build -t xabimoreno/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xabimoreno/react-test npm test -- --coverage

after_sucess:
  - docker build -t xabimoreno/multi-client ./client
  - docker build -t xabimoreno/multi-nginx ./nginx
  - docker build -t xabimoreno/multi-server ./server
  - docker build -t xabimoreno/multi-worker ./worker
  #Login docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images to docker hub
  - docker push xabimoreno/multi-client
  - docker push xabimoreno/multi-nginx
  - docker push xabimoreno/multi-server
  - docker push xabimoreno/multi-worker